replicaCount: 1

image:
  repository: tessarine/room-intrusion-detector
  pullPolicy: IfNotPresent
  tag: "sha-c8e5602"

kafka:
  bootstrapServers: "datafabric01.ezmeral.demo.hpelabs.fr:9092"
  topic: "room-intrusion-events"

s3:
  endpointUrl: "https://datafabric01.ezmeral.demo.hpelabs.fr:9000"
  bucketName: "room-surveillance-snapshots"
  region: "us-east-1"

env:
  roomName: "Server-Room-04"
  cameraRTSPUrl: "rtsp://camera-device-ip:554/stream1"
  confidenceThreshold: "0.75"

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
    nvidia.com/gpu: "0"
  requests:
    cpu: 500m
    memory: 1Gi
