apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "room-intrusion-detector.fullname" . }}-config
data:
  ROOM_NAME: {{ .Values.env.roomName | quote }}
  CAMERA_RTSP_URL: {{ .Values.env.cameraRTSPUrl | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
  CONFIDENCE_THRESHOLD: {{ .Values.env.confidenceThreshold | quote }}
  S3_ENDPOINT_URL: {{ .Values.s3.endpointUrl | quote }}
  S3_BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
