apiVersion: v1
kind: Secret
metadata:
  name: {{ include "room-intrusion-detector.fullname" . }}-s3-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "SPPGA7TKVWQVLHIC4S18JEFFTMJYC1U"
  AWS_SECRET_ACCESS_KEY: "L16RXLGZVJ8CYLQX9QA7RU4FJ8CJJIM8WMP9UQ1O0IWCAHD3L5UTQ12XUJV1XT2ABJACTQ16LWDYX06U2U51UDJKJAT1DJEU7PCVPZJB2"
